# Generated by Django 2.2 on 2021-09-12 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excelformatter_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Order',
        ),
    ]
