# Generated by Django 2.2 on 2021-09-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelformatter_app', '0002_remove_book_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
