# Generated by Django 2.2 on 2021-09-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelformatter_app', '0003_auto_20210911_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='users_tracking',
            field=models.ManyToManyField(related_name='tracked_books', to='excelformatter_app.User'),
        ),
    ]
